"""description of your changes

Revision ID: 7aff1d5e6e4c
Revises: 8822ac5dd2e2
Create Date: 2024-06-08 02:28:37.112756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aff1d5e6e4c'
down_revision: Union[str, None] = '8822ac5dd2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('title', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
