"""description of your changes

Revision ID: 8822ac5dd2e2
Revises: 
Create Date: 2024-06-08 02:27:45.915362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8822ac5dd2e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_my_model_id', table_name='my_model')
    op.drop_index('ix_my_model_name', table_name='my_model')
    op.drop_table('my_model')
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.create_table('my_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_my_model_name', 'my_model', ['name'], unique=1)
    op.create_index('ix_my_model_id', 'my_model', ['id'], unique=False)
    # ### end Alembic commands ###
